[phases.setup]
apt = ["libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxrender1", "libxext6"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install opencv-python-headless --force-reinstall --no-deps"
]
